### ISSUE TITLE
[BUG] Android Image Upload

### ISSUE THREAD

**Issue by jenisgrindstaff** [RocketChat/Rocket.Chat.Android#1050]
**Your Rocket.Chat.Android version:** 2.0.0-beta5
**Mobile device model and OS version:** Pixel 2 / 8.1.0
**Server Version:** 0.63.0

Steps to reproduce:
1. Click + to upload files
2. Select Image to upload
3. Error
![screenshot_20180407-090110](https://user-images.githubusercontent.com/737621/38458861-dade99cc-3a70-11e8-8e34-35a107489118.png)

The same image will work when uploading via the web client and also iOS client so I don't think it is a size limitation on the server.  

Do clients have a separate max upload file size?  Screen shoots which are smaller in size will upload fine via the android app.  

For reference the image that fails is 3.2 MB.  
Screen shot size that works is 194 KB.

A little more digging on this.  It looks like the web client POSTs to a different url then the android client:

**Web:**

> https://chat.frog.org/ufs/GridFS:Uploads/iaunciPubv8aXG8wn?token=7B79a89858&progress=0.035919505580633636

**Android:**

> https://chat.frog.org/api/v1/rooms.upload/r9uEmTdyShwWjms8Grocket.cat

**Logs**

```
04-07 11:41:38.578 31970  9631 D null    : Server: nginx/1.4.6 (Ubuntu)
04-07 11:41:38.578 31970  9631 D null    : Date: Sat, 07 Apr 2018 15:41:39 GMT
04-07 11:41:38.578 31970  9631 D null    : Content-Type: text/html
04-07 11:41:38.578 31970  9631 D null    : Content-Length: 207
04-07 11:41:38.578 31970  9631 D null    : Connection: close
04-07 11:41:38.582 31970  9631 D null    : <html>
04-07 11:41:38.582 31970  9631 D null    : <head><title>413 Request Entity Too Large</title></head>
04-07 11:41:38.582 31970  9631 D null    : <body bgcolor="white">
04-07 11:41:38.582 31970  9631 D null    : <center><h1>413 Request Entity Too Large</h1></center>
04-07 11:41:38.582 31970  9631 D null    : <hr><center>nginx/1.4.6 (Ubuntu)</center>
04-07 11:41:38.582 31970  9631 D null    : </body>
04-07 11:41:38.582 31970  9631 D null    : </html>
04-07 11:41:38.582 31970  9631 D null    : <-- END HTTP (207-byte body)
04-07 11:41:38.582 31970  9631 D null    : SDK(https://chat.frog.org): Successful HTTP request: POST - https://chat.frog.org/api/v1/rooms.upload/r9uEmTdyShwWjms8Grocket.cat: 413 Request Entity Too Large
04-07 11:41:38.582 31970  9631 D null    : SDK(https://chat.frog.org): Error body: <html>
04-07 11:41:38.582 31970  9631 D null    : <head><title>413 Request Entity Too Large</title></head>
04-07 11:41:38.582 31970  9631 D null    : <body bgcolor="white">
04-07 11:41:38.582 31970  9631 D null    : <center><h1>413 Request Entity Too Large</h1></center>
04-07 11:41:38.582 31970  9631 D null    : <hr><center>nginx/1.4.6 (Ubuntu)</center>
04-07 11:41:38.582 31970  9631 D null    : </body>
04-07 11:41:38.582 31970  9631 D null    : </html>
04-07 11:41:38.583 31970 31970 D null    : chat.rocket.common.RocketChatApiException: Use JsonReader.setLenient(true) to accept malformed JSON at path $(url='https://chat.frog.org/api/v1/rooms.upload/r9uEmTdyShwWjms8Grocket.cat')
04-07 11:41:38.583 31970 31970 D null    : 	at chat.rocket.core.internal.rest.RestClientKt.processCallbackError(RestClient.kt:152)
04-07 11:41:38.583 31970 31970 D null    : 	at chat.rocket.core.internal.rest.RestClientKt$handleRestCall$$inlined$suspendCancellableCoroutine$lambda$1.onResponse(RestClient.kt:80)
04-07 11:41:38.583 31970 31970 D null    : 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
04-07 11:41:38.583 31970 31970 D null    : 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
04-07 11:41:38.583 31970 31970 D null    : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
04-07 11:41:38.583 31970 31970 D null    : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
04-07 11:41:38.583 31970 31970 D null    : 	at java.lang.Thread.run(Thread.java:764)
04-07 11:41:38.583 31970 31970 D null    : Caused by: com.squareup.moshi.JsonEncodingException: Use JsonReader.setLenient(true) to accept malformed JSON at path $
04-07 11:41:38.583 31970 31970 D null    : 	at com.squareup.moshi.JsonReader.syntaxError(JsonReader.java:220)
04-07 11:41:38.583 31970 31970 D null    : 	at com.squareup.moshi.JsonUtf8Reader.checkLenient(JsonUtf8Reader.java:1012)
04-07 11:41:38.583 31970 31970 D null    : 	at com.squareup.moshi.JsonUtf8Reader.doPeek(JsonUtf8Reader.java:345)
04-07 11:41:38.583 31970 31970 D null    : 	at com.squareup.moshi.JsonUtf8Reader.peek(JsonUtf8Reader.java:172)
04-07 11:41:38.583 31970 31970 D null    : 	at chat.rocket.common.internal.KotshiErrorMessageJsonAdapter.fromJson(KotshiErrorMessageJsonAdapter.java:40)
04-07 11:41:38.583 31970 31970 D null    : 	at chat.rocket.common.internal.KotshiErrorMessageJsonAdapter.fromJson(KotshiErrorMessageJsonAdapter.java:13)
04-07 11:41:38.583 31970 31970 D null    : 	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:41)
04-07 11:41:38.583 31970 31970 D null    : 	at chat.rocket.core.internal.rest.RestClientKt.processCallbackError(RestClient.kt:147)
04-07 11:41:38.583 31970 31970 D null    : 	... 6 more
04-07 11:41:38.752   832   832 E cnss-daemon: wlan_service_update_sys_param: unable to open /proc/sys/net/ipv4/tcp_limit_output_bytes
04-07 11:41:40.609  1110  1110 W WindowManager: removeWindowToken: Attempted to remove non-existing token: android.os.Binder@8ae5f50
04-07 11:41:41.592  1574  1574 E QtiImsExtUtils: getConfigForPhoneId phoneId is invalid
04-07 11:41:41.592  1574  1574 E QtiImsExtUtils: isCarrierConfigEnabled bundle is null
```

**Comment by bkraul** [comment]
I see several issues mentioning this issue. Some that have been closed, like #818 suggest that the latest version of the server is required by the client. However, this issue seems to persist even on the latest version. Is this the right issue to track resolution?

**Comment by rafaelks** [comment]
@bkraul @jenisgrindstaff What version of the server & app are guys using?

**Comment by timowilson-fluke** [comment]
This happened to me as well. I had to increase the nginx ```client_max_body_size``` value in nginx.config (I increased my value to 25M) as well as change the setting in the File Upload setting in the Rocket Chat server Administration area. After I restart nginx (and Rocket Chat), I was able to transfer larger files from the mobile device without getting this error.

**Comment by jenisgrindstaff** [comment]
@rafaelks I am using 0.63.3 on the server and 2.0.2 for the app. 

As I mentioned in my original post, the same image works on iOS and the desktop.

**Comment by bkraul** [comment]
@rafaelks my versions of server and client are the same as @jenisgrindstaff, furthermore, the picture is 1.8MB, so upload size is definitely not an issue.  And same, uploads work on desktop apps just fine.

**Comment by kvozi** [comment]
Hi. Same problem.



![screenshot_20180423-042320](https://user-images.githubusercontent.com/38634495/39099566-980bc6e2-46af-11e8-858a-434d3b62e4c4.png)


**Your Rocket.Chat.Android version:** 2.0.1 (GP)
**Mobile device model and OS version:** Xiaomi Redmi 1S / 7.1.2 LineageOS 14.1
**Server Version:** 0.63.3

Steps to reproduce:

Click + to upload files
Select Image to upload
Error

But some small pictures (screenshots for example) sent successfully.

upd: Adding client_max_body_size 200M; in nginx.conf fixed problem for me but I'm not sure if it's right way.

**Comment by jenisgrindstaff** [comment]
@kvozi Did you have issues uploading from the desktop client before making the nginx.conf change?

**Comment by jenisgrindstaff** [comment]
All - changing nginx.conf client_max_body_size to a larger size worked for me.  

It is interesting that without this change the same file would work via the desktop and iOS clients.

**Comment by kvozi** [comment]
@jenisgrindstaff I did not have any issues uploading from the desktop client before making the nginx.conf change. The same situation as you - problems only with the android application, which are solved by editing nginx.conf, thanks @timowilson-fluke for this hint.

**Comment by bkraul** [comment]
@rafaelks, just curious, since this issue was closed by the OP, but the conditions do not seem to apply to the rest of us who are still having the problem, is there another issue we need to track this on, or can this be reopened?

Furthermore, having a docker-based installation, where would I need to change the nginx configuration? I will take a look at my proxy, perhaps the issue is there.

**Comment by bkraul** [comment]
After taking a look at my docker proxy (using [jwilder/nginx-proxy](https://hub.docker.com/r/jwilder/nginx-proxy/)) I was able to identify the place where I needed to adjust the ```client_max_body_size``` setting (preferences guide for the proxy is [here](https://github.com/jwilder/nginx-proxy#per-virtual_host)). I set it to 100m, and the problem was resolved as described above. Thank you all for your feedback.

**Comment by localguru** [comment]
Same here:

Nginx error log:
```
2018/11/15 14:49:26 [error] 23778#23778: *210300 client intended to send too large chunked body: 1056768 bytes, client: x, server: x, request: "POST /api/v1/rooms.upload/dbcZmYQRn6X9Brtk6 HTTP/2.0", host: "x"
```
`client_max_body_size` fixed it. Thanks!

**Comment by EGTITS** [comment]
i confirm. add/edit ngnx.conf client _max_body_size xM; fixed the problem with both last versions for app and rocketchat server 0.73.2

**Comment by djz88** [comment]
Still present when using server version 0.74.3 with file  upload limit 20MB. This looks like an issue with application(using latest version).

picture with disk size: 695.09 KB (711 777 Bytes) cannot be uploded via app. Maybe be the issue handling of pictures by app? Because this particular image has 27.85  MB (29 203 240 Bytes) in memory.
