### ISSUE TITLE
[BUG] 2FA not working on versions 2.0.4, 2.1.0+

### ISSUE THREAD

**Issue by dsgagi** [RocketChat/Rocket.Chat.Android#1226]
## Description

After updating Android client to 2.0.4, 2FA stopped working. Same code returns "Invalid 2FA code" on Android client, but works in the webclient/browser on desktop computers or smartphones.

## Devices and Versions

Your Rocket.Chat.Android version: 2.0.4
Your Rocket.Chat Server version: 0.63.3

Mobile device model and OS version: Huawei P10 Lite - Android 7.0

## Steps to reproduce
1. Sign in to the server
2. Login - login credentials are accepted
3. 2FA code prompt appears
4. After copy&pasting 2fa code from authy, app returns "Invalid 2FA Code" message

Cheers,
Dragan

**Comment by rafaelks** [comment]
@dragans Is your device clock synced correctly?

**Comment by dsgagi** [comment]
Hi. Yes, it is synced to my mobile network operator clock and the time is in sync with the rchat server too.

That was first thing that came to mind also.

I also tried increasing the 2FA delta in the server settings and reinstalling the mobile app, but no luck :)

**Comment by rafaelks** [comment]
@dragans Can you check version 2.1.0 that we just released to the store?

**Comment by dsgagi** [comment]
Still the same unfortunately. I also updated the server version to the 0.64.1.

I forgot to try it before, but trying the generated 2FA backup codes also doesn't work on mobile.

**Comment by dsgagi** [comment]
Just tried testing 2FA on the colleagues phone too, same result.

Mobile device model and OS version: OnePlus 3T - Android 8.0

**Comment by rafaelks** [comment]
@dragans Have you checked if your server's clock configured correctly? I can use 2FA normally here on my device. Can you try using our server with 2FA? https://open.rocket.chat. Thanks!

**Comment by dsgagi** [comment]
I tried with https://open.rocket.chat/ and it works OK, so it seems it's something related to our setup.

It's weird that 2FA code works in browsers on the mobile devices, but not in Android app (with our server). I checked timezone and time on the server, everything is configured correctly and time is synchronized.

Any tip on what else could be the problem maybe? :)

Nothing was changed on the server, except that I updated to the latest stable. Before switching to the new Android app, 2FA worked OK.

**Comment by rafaelks** [comment]
@dragans Could you please try removing 2FA from your account and adding it again?

**Comment by dsgagi** [comment]
Tried that several times too :)

EDIT: For reference, here are timezone settings that are set on the server and my android device.

Server: Europe/Belgrade (Central Europe Standard Time); Ubuntu 16.04 server
Android device: Uses mobile network-provided time, automatic timezone settings, current timezone is GMT+02:00 Central Europe Standard Time

**Comment by earlng** [comment]
@rafaelks I'm also experiencing this problem. And actually, I tried connecting to open.rocket.chat with 2FA via the Android App. I'm also getting a similar error "Invalid Code". So I'm getting similar responses when I try to connect to our self-hosted instance, and yours.

**Comment by carlosmbpereira** [comment]
Hello,
I'm having the same issue.
None of our users in our rocket.chat instance can't use 2FA in Android.
In the web everything works flawless.

Server version: 0.65.1
Android Version: 2.3.2 build 2026 (available in the Google Play store)

**Comment by rafaelks** [comment]
Guys, we're investigating the issue and we'll get back to you soon with a resolution. 👍

**Comment by philipbrito** [comment]
Very hard to get this bug @dsgagi @earlng and @masterdbpereira 
I tried here several times with our open.rocket.chat server and didn't get the bug. Have a look: https://drive.google.com/file/d/11EzwTSIN6PEbvSEY2TPQqhqqqXelbDMj

Could you try again and let me know if it is happening yet to you guys?

c/c @rafaelks

**Comment by dsgagi** [comment]
Thing is, Android 2FA works for open.rocket.chat server but not for our self-deployed server.

2FA codes work for web and desktop clients, just not for the Android app. Not sure if the same happens for iOS app, didn't have an opportunity to test it.

Maybe the Android app was hardcoded with open.rocket.chat for 2FA code validation during testing and left with that change? :)

**Comment by rafaelks** [comment]
@dsgagi Validation is done server-side not client-side. What's your server URL so we can give it a try and debug on the API-side?

**Comment by dsgagi** [comment]
@rafaelks I am sending you credentials for our server, as public registrations are not opened.

**Comment by HammyHavoc** [comment]
Any ETA for 2FA being functional on the native Android apps? Seems silly that we can't use this yet.

**Comment by rafaelks** [comment]
@HammyHavoc @dsgagi Tried with several devices on @dsgagi and works for me. Really can't understand why it doesn't work for you guys. Can you all try different timezones? Setting up a new key maybe? Thanks!

**Comment by HammyHavoc** [comment]
@rafaelks I don't know whether or not it works, I was assuming that this message wouldn't be here if it did work:
![capture](https://user-images.githubusercontent.com/503951/42295809-1ee57de2-7fe6-11e8-8539-8600c7db4988.PNG)

**Comment by dsgagi** [comment]
@HammyHavoc That message is little misleading :)

There were two versions of Android apps on Play store, Rocket.Chat+ and Rocket.Chat.

Rocket.Chat+ is an old app and is now deprecated, but some users are probably still using it. It also doesn't support 2FA.

https://play.google.com/store/apps/details?id=chat.rocket.android&hl=en - this one is currently supported and has 2FA support too.

**Comment by rafaelks** [comment]
@HammyHavoc Looks like your Rocket.Chat server is not up-to-date... can you try updating it? The apps supports 2FA for more than 1 year now. 🤔

**Comment by HammyHavoc** [comment]
@rafaelks so I just enabled it and it works beautifully. Amazing work!

**Comment by philipbrito** [comment]
Ok, this issue is gone for @dsgagi and @HammyHavoc, right?
And about you @earlng and @masterdbpereira, is it working now?
Just let me know and let's close this issue.

**Comment by dsgagi** [comment]
Still happens unfortunately. We also tried in Android Studio emulator and the same thing happens.

I'm attaching sanitized debug output from the emulator. We user Android Oreo + Pixel 2 profile. 
[rChat android debug output.txt](https://github.com/RocketChat/Rocket.Chat.Android/files/2172789/rChat.android.debug.output.txt)

**Comment by rafaelks** [comment]
Just pasting here the reply to your email:

I’m thinking that maybe the problem is a different issue… look at this:

**Request with a valid TOTP:**

```
curl -X POST "https://rchat.netcast.rs/api/v1/login" -H "Content-Type: application/json" -d '{"username":"(private)","password":"(private)","code":"336300"}'
{"status":"success","data":{"userId":"ufB8RGgAtRmRFqbif","authToken":"(private)","me":{"_id":"ufB8RGgAtRmRFqbif","name":"Rocket Chat support","emails":[{"address":"(private)","verified":true}],"status":"offline","statusConnection":"offline","username":"rc.support","utcOffset":-3,"active":true,"roles":["user"],"settings":{"preferences":{"idleTimeLimit":300,"enableAutoAway":true,"desktopNotificationDuration":10000,"audioNotifications":"mentions","desktopNotifications":"mentions","mobileNotifications":"all","unreadAlert":true,"useEmojis":true,"convertAsciiEmoji":true,"autoImageLoad":true,"saveMobileBandwidth":true,"collapseMediaByDefault":false,"hideUsernames":false,"hideRoles":false,"hideFlexTab":false,"hideAvatars":false,"roomsListExhibitionMode":"category","mergeChannels":false,"sendOnEnter":"normal","viewMode":0,"emailNotificationMode":"mentions","roomCounterSidebar":false,"newRoomNotification":"door","newMessageNotification":"chime","notificationsSoundVolume":100,"sidebarShowUnread":true,"sidebarShowFavorites":true,"muteFocusedConversations":true,"sidebarViewMode":"medium","sidebarHideAvatar":false,"messageViewMode":0,"sidebarGroupByType":true}},"email":"(private)"}}}
```

**Request with invalid TOTP:**

```
curl -X POST "https://rchat.netcast.rs/api/v1/login" -H "Content-Type: application/json" -d '{"username":"(private)","password":"(private)","code":"336300"}'
{"status":"error","error":"totp-invalid","message":"TOTP Invalid"}
```

The response for your user is different than the one I’m getting… let me ask you a question: do you guys have any custom field, or any change in the code or just normal deploy?

**Comment by dsgagi** [comment]
We used manual install method on Ubuntu distro from the docs and we are running the app behind nginx. Didn't make any changes to the code.

Just checked app settings, custom field settings are all blank.

**Comment by rafaelks** [comment]
@dsgagi I created this issue in our core repo to get more feedback, let's wait for them: https://github.com/RocketChat/Rocket.Chat/issues/11407

**Comment by dsgagi** [comment]
Hello, one interesting update about this issue.

2FA started working for the colleague on whose phone we also tested before. Phone model OnePlus 3T, Android 8.0. Interesting thing is that 2FA started working after he installed Android July 2018 security update.

On my Huawei P10 Lite with Android 8.0.0 it still doesn't work, but I'm still on June 2018 security update. Hope that I will receive July 2018 update soon, so I can test again.

**Comment by dsgagi** [comment]
Installed the July security update, but 2FA still doesn't work unfortunately.

**Comment by rafaelks** [comment]
@dsgagi Are you still having this problem in 2.6.0?

**Comment by dsgagi** [comment]
Hi @rafaelks. I still have this issue.

As mentioned before, now I'm 99% sure it's something OS related on my Huawei P10 lite (with up to date OS). Colleague also had the same problem on his OnePlus 3T, before applying Android security July 2018 patch.

I had hoped that installing the same patch would fix the issue for me too, but unfortunately it didn't.

I understand that this is pretty weird and will be really hard to debug :)

**Comment by rafaelks** [comment]
@dsgagi Gotcha! Thanks for the update! 👍

**Comment by rafaelks** [comment]
@dsgagi Have you tried the login with your username? We just noticed that with email it doesn't work: https://github.com/RocketChat/Rocket.Chat.Android/issues/1705. Going to fix that real soon.

**Comment by dsgagi** [comment]
Hehe, this is embarrassing :D

It works with username, but it doesn't with email. SwiftKey app always suggested email address while inputting, and it never crossed my mind to try with username...

**Comment by rafaelks** [comment]
LOL! OK, our failure... we're going to fix this for next release. 👍

**Comment by philipbrito** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat.Android/pull/1728
