### ISSUE TITLE
[BUG] Sorry, an error has occurred, please try again - 1.0.2

### ISSUE THREAD

**Issue by ugzv** [RocketChat/Rocket.Chat.Android#2308]
## Describe the bug
Before upgrading the server version to the latest 1.0.2 I was able to see channels and chat was working normally. Now every time I open the app I get the following error:
_Sorry, an error has occurred, please try again._ 

I tried another Android phone and got the same error. I also tried the experimental app, and there everything was blank.

## To Reproduce
A1. Open Rocket.Chat app
A2. I got error

B1. Open Rocket.Chat Experimental
B2.  I see blank content

## Screenshots
![Rocket.Cha](https://pixtis.com/m7heat8P.png)
![Rocket.Chat Experimental](https://pixtis.com/26tail7N.png)

## Devices and Versions
Your Rocket.Chat.Android version: 3.3.1
Your Rocket.Chat Server version: 1.0.2

Google Pixel 3XL (Android Q) and Huawei P20pro (Android 9)

## Additional context
I tried uninstalling apps and deleting app content without success. I also tried signing up with another newly created account and it didn't work.

**Comment by reetp** [comment]
How did you deploy Rocketchat?
What do the Rocketchat logs tell you?

**Comment by reetp** [comment]
Seems very similar to 
https://github.com/RocketChat/Rocket.Chat.Android/issues/2225

**Comment by ugzv** [comment]
We've deployed Rocket Chat with docker-compose and we're using Nginx. 

The logs shows this after logging in:
```
API ➔ debug POST: /api/v1/login
API ➔ debug GET: /api/v1/me
API ➔ debug Success { statusCode: 200,
body:
{ _id: 'jwM8X9PM6D9hEMWD8',
name: 'temp',
emails: [ [Object] ],
status: 'offline',
statusConnection: 'offline',
username: 'temp',
utcOffset: undefined,
active: true,
language: undefined,
roles: [ 'admin' ],
settings: { preferences: [Object] },
customFields: undefined,
email: undefined,
avatarUrl: 'https://OUR_URL/avatar/temp',
success: true } }
API ➔ debug GET: /api/v1/settings.public?count=0&fields=%7B%22type%22%3A%201%7D&query=%7B%22_id%22%3A%20%7B%22%24in%22%3A%20%5B%22uniqueID%22%2C%22LDAP_Enable%22%2C%22CAS_enabled%22%2C%22CAS_login_url%22%2C%22Accounts_RegistrationForm%22%2C%22Accounts_ShowFormLogin%22%2C%22Accounts_PasswordReset%22%2C%22Accounts_CustomFields%22%2C%22Accounts_OAuth_Google%22%2C%22Accounts_OAuth_Facebook%22%2C%22Accounts_OAuth_Github%22%2C%22Accounts_OAuth_Linkedin%22%2C%22Accounts_OAuth_Meteor%22%2C%22Accounts_OAuth_Twitter%22%2C%22Accounts_OAuth_Gitlab%22%2C%22API_Gitlab_URL%22%2C%22Accounts_OAuth_Wordpress%22%2C%22API_Wordpress_URL%22%2C%22Jitsi_Enabled%22%2C%22Jisti_Enable_Channels%22%2C%22Jitsi_SSL%22%2C%22Jitsi_Domain%22%2C%22Jitsi_URL_Room_Prefix%22%2C%22Site_Url%22%2C%22Site_Name%22%2C%22Assets_favicon_512%22%2C%22Assets_favicon_192%22%2C%22UI_Use_Real_Name%22%2C%22UI_Allow_room_names_with_special_chars%22%2C%22Favorite_Rooms%22%2C%22FileUpload_Storage_Type%22%2C%22FileUpload_MaxFileSize%22%2C%22FileUpload_MediaTypeWhiteList%22%2C%22Message_HideType_uj%22%2C%22Message_HideType_ul%22%2C%22Message_HideType_au%22%2C%22Message_HideType_mute_unmute%22%2C%22Message_HideType_ru%22%2C%22Message_AllowDeleting%22%2C%22Message_AllowEditing%22%2C%22Message_AllowPinning%22%2C%22Message_AllowStarring%22%2C%22Message_ShowDeletedStatus%22%2C%22Message_ShowEditedStatus%22%2C%22Assets_tile_310_wide%22%2C%22Store_Last_Message%22%2C%22Message_Read_Receipt_Enabled%22%2C%22Message_Read_Receipt_Store_Users%22%5D%7D%7D
API ➔ debug GET: /api/v1/permissions
API ➔ debug Success { statusCode: 200,
body:
{ settings:
[ [Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object] ],
count: 47,
offset: 0,
total: 47,
success: true } }
The endpoint "permissions" is deprecated and will be removed after version v0.69
API ➔ debug Success { statusCode: 200,
body:
[ { _id: 'access-mailer',
roles: [Array],
_updatedAt: 2019-05-06T09:12:18.868Z },
{ _id: 'access-permissions',
roles: [Array],
_updatedAt: 2018-09-06T07:37:31.981Z },
{ _id: 'add-oauth-service',
roles: [Array],
_updatedAt: 2018-09-06T07:37:31.984Z },
{ _id: 'add-user-to-any-c-room',
roles: [Array],
_updatedAt: 2018-09-06T07:37:31.991Z },
{ _id: 'add-user-to-any-p-room',
roles: [Array],
_updatedAt: 2018-09-06T08:11:37.418Z },
{ _id: 'add-user-to-joined-room',
roles: [Array],
_updatedAt: 2018-09-06T07:37:31.988Z },
{ _id: 'api-bypass-rate-limit',
roles: [Array],
_updatedAt: 2019-02-24T23:55:55.789Z },
{ _id: 'archive-room',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.025Z },
{ _id: 'assign-admin-role',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.028Z },
{ _id: 'assign-roles',
roles: [Array],
_updatedAt: 2019-04-28T18:31:16.932Z },
{ _id: 'auto-translate',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.510Z },
{ _id: 'ban-user',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.031Z },
{ _id: 'bulk-create-c',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.034Z },
{ _id: 'bulk-register-user',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.037Z },
{ _id: 'call-management',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.440Z },
{ _id: 'clean-channel-history',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.053Z },
{ _id: 'close-livechat-room',
roles: [Array],
_updatedAt: 2019-05-06T09:12:18.880Z },
{ _id: 'close-others-livechat-room',
roles: [Array],
_updatedAt: 2019-05-06T09:12:18.883Z },
{ _id: 'create-c',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.041Z },
{ _id: 'create-d',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.044Z },
{ _id: 'create-p',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.048Z },
{ _id: 'create-personal-access-tokens',
roles: [Array],
_updatedAt: 2018-11-28T18:38:26.696Z },
{ _id: 'create-user',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.051Z },
{ _id: 'delete-c',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.056Z },
{ _id: 'delete-d',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.060Z },
{ _id: 'delete-message',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.068Z },
{ _id: 'delete-p',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.071Z },
{ _id: 'delete-user',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.074Z },
{ _id: 'edit-message',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.077Z },
{ _id: 'edit-other-user-active-status',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.081Z },
{ _id: 'edit-other-user-avatar',
roles: [Array],
_updatedAt: 2019-04-28T18:31:16.947Z },
{ _id: 'edit-other-user-info',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.254Z },
{ _id: 'edit-other-user-password',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.259Z },
{ _id: 'edit-privileged-setting',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.262Z },
{ _id: 'edit-room',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.265Z },
{ _id: 'edit-room-retention-policy',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.269Z },
{ _id: 'force-delete-message',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.272Z },
{ _id: 'join-without-join-code',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.275Z },
{ _id: 'leave-c',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.278Z },
{ _id: 'leave-p',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.281Z },
{ _id: 'mail-messages',
roles: [Array],
_updatedAt: 2019-05-06T09:12:17.681Z },
{ _id: 'manage-apps',
roles: [Array],
_updatedAt: 2019-05-06T09:12:15.189Z },
{ _id: 'manage-assets',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.284Z },
{ _id: 'manage-cloud',
roles: [Array],
_updatedAt: 2019-05-06T09:12:07.982Z },
{ _id: 'manage-emoji',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.287Z },
{ _id: 'manage-integrations',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.291Z },
{ _id: 'manage-oauth-apps',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.302Z },
{ _id: 'manage-own-integrations',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.293Z },
{ _id: 'manage-sounds',
roles: [Array],
_updatedAt: 2019-05-06T09:12:17.732Z },
{ _id: 'mention-all',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.310Z },
{ _id: 'mention-here',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.313Z },
{ _id: 'mute-user',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.316Z },
{ _id: 'pin-message',
roles: [Array],
_updatedAt: 2019-05-06T09:12:17.934Z },
{ _id: 'post-readonly',
roles: [Array],
_updatedAt: 2019-05-06T09:12:17.669Z },
{ _id: 'preview-c-room',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.432Z },
{ _id: 'remove-closed-livechat-rooms',
roles: [Array],
_updatedAt: 2019-05-06T09:12:18.888Z },
{ _id: 'remove-user',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.322Z },
{ _id: 'reset-other-user-e2e-key',
roles: [Array],
_updatedAt: 2018-11-28T18:38:26.718Z },
{ _id: 'run-import',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.326Z },
{ _id: 'run-migration',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.329Z },
{ _id: 'save-others-livechat-room-info',
roles: [Array],
_updatedAt: 2019-05-06T09:12:18.886Z },
{ _id: 'send-many-messages',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.342Z },
{ _id: 'set-leader',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.345Z },
{ _id: 'set-moderator',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.334Z },
{ _id: 'set-owner',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.337Z },
{ _id: 'set-react-when-readonly',
roles: [Array],
_updatedAt: 2019-05-06T09:12:17.678Z },
{ _id: 'set-readonly',
roles: [Array],
_updatedAt: 2019-05-06T09:12:17.673Z },
{ _id: 'snippet-message',
roles: [Array],
_updatedAt: 2019-05-06T09:12:17.942Z },
{ _id: 'start-discussion',
roles: [Array],
_updatedAt: 2019-04-28T18:31:28.830Z },
{ _id: 'start-discussion-other-user',
roles: [Array],
_updatedAt: 2019-04-28T18:31:28.888Z },
{ _id: 'unarchive-room',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.348Z },
{ _id: 'user-generate-access-token',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.354Z },
{ _id: 'view-broadcast-member-list',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.437Z },
{ _id: 'view-c-room',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.351Z },
{ _id: 'view-d-room',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.357Z },
{ _id: 'view-full-other-user-info',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.371Z },
{ _id: 'view-history',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.379Z },
{ _id: 'view-join-code',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.392Z },
{ _id: 'view-joined-room',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.389Z },
{ _id: 'view-l-room',
roles: [Array],
_updatedAt: 2019-05-06T09:12:18.873Z },
{ _id: 'view-livechat-analytics',
roles: [Array],
_updatedAt: 2019-05-06T09:12:18.891Z },
{ _id: 'view-livechat-manager',
roles: [Array],
_updatedAt: 2019-05-06T09:12:18.875Z },
{ _id: 'view-livechat-rooms',
roles: [Array],
_updatedAt: 2019-05-06T09:12:18.878Z },
{ _id: 'view-logs',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.399Z },
{ _id: 'view-other-user-channels',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.402Z },
{ _id: 'view-outside-room',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.434Z },
{ _id: 'view-p-room',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.408Z },
{ _id: 'view-privileged-setting',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.411Z },
{ _id: 'view-room-administration',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.421Z },
{ _id: 'view-statistics',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.424Z },
{ _id: 'view-user-administration',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.429Z },
success: true ] }
API ➔ debug GET: /api/info
API ➔ debug Success { statusCode: 200, body: { version: '1.0.2', success: true } }
API ➔ debug GET: /api/v1/me
API ➔ debug GET: /api/v1/emoji-custom
The endpoint "emoji-custom" is deprecated and will be removed after version v1.12.0
Meteor ➔ method listEmojiCustom -> userId: null , arguments: [ {} ]
API ➔ debug Success { statusCode: 200,
body:
{ _id: 'jwM8X9PM6D9hEMWD8',
name: 'temp',
emails: [ [Object] ],
status: 'offline',
statusConnection: 'offline',
username: 'temp',
utcOffset: undefined,
active: true,
language: undefined,
roles: [ 'admin' ],
settings: { preferences: [Object] },
customFields: undefined,
email: undefined,
avatarUrl: 'https://OUR_URL/avatar/temp',
success: true } }
The endpoint "emoji-custom" is deprecated and will be removed after version 1.12.0
API ➔ debug Success { statusCode: 200,
body:
{ emojis:
[ [Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object] ],
success: true } }
API ➔ debug POST: /api/v1/push.token
API ➔ debug Success { statusCode: 200,
body:
{ result:
{ token: [Object],
appName: 'Main',
userId: 'jwM8X9PM6D9hEMWD8',
enabled: true,
createdAt: 2019-05-09T12:12:14.131Z,
updatedAt: 2019-05-09T12:12:14.131Z,
_id: 'TYGyvQQnqgJwFYjbf' },
success: true } }
Meteor ➔ publish null -> userId: null , arguments: []
Meteor ➔ publish null -> userId: jwM8X9PM6D9hEMWD8 , arguments: []
API ➔ debug GET: /api/v1/rooms.get
Meteor ➔ method rooms/get -> userId: jwM8X9PM6D9hEMWD8 , arguments: [ undefined ]
API ➔ debug Success { statusCode: 200,
body: { update: [ [Object] ], remove: [], success: true } }
Meteor ➔ publish userData -> userId: jwM8X9PM6D9hEMWD8 , arguments: []
Meteor ➔ publish activeUsers -> userId: jwM8X9PM6D9hEMWD8 , arguments: []
```

**Comment by ChrissW-R1** [comment]
We have the same problem. A third of our users could use the Android app anymore.

I attached a log in debug mode, which contains every items, which appear, while someone is opening the app:
[rocket.chat.log](https://github.com/RocketChat/Rocket.Chat.Android/files/3162362/rocket.chat.log)
(all personal information were replaced by x's)

We have installed the 1.0.1 server version and the newest Android app.

**Comment by andypost** [comment]
After #2223 few chats still not accessible from beta android, endless spinner in the middle of chat window

**Comment by philipbrito** [comment]
Guys, we just released `3.3.2` version on the Play Store. Could you try it, please?
Thanks.

**Comment by andypost** [comment]
Yay! It fixed blicked chats and avatars are back to chat list

**Comment by Crazy-Hopper** [comment]
3.3.2 doesn't fix the issue for me unfortunately :-(
Just as before, chats won't show up while connecting to my server, but they are shown when connected to open.r.c
The search finds public channels and contacts, but when i open up the public channel it shows the preloader for some time but then says "No chat messages".

**Comment by hkbnman** [comment]
Tried android rocketchat app 3.3.2, still showed "The required "roomId" or "roomname" param provided does not match any channel [error-room-not-found] if I click on any new message from livechat and there is no way to reply for that message from app

**Comment by Crazy-Hopper** [comment]
> Tried android rocketchat app 3.3.2, still showed "The required "roomId" or "roomname" param provided does not match any channel [error-room-not-found] if I click on any new message from livechat and there is no way to reply for that message from app

That seems to be a different bug.

**Comment by ugzv** [comment]
> Guys, we just released `3.3.2` version on the Play Store. Could you try it, please?
> Thanks.

I can confirm that after upgrading to the latest version _3.3.2_ everything is back to normal.

Thank you, guys.

**Comment by ChrissW-R1** [comment]
> Guys, we just released `3.3.2` version on the Play Store. Could you try it, please?
> Thanks.

No, everything the same. We also updated to the server version 1.0.3 and nothing changed.
- Update app? - Doesn't help
- Login again? - Doesn't help
- Reinstall app? - Doesn't help

**Comment by Hilzerak** [comment]
Same here,
Rocketchat 1.0.3 - no error in Logfile
AppVersion 3.3.2

Can login, Can search for Users / Channels but if any channel is selected an inifity loop with "Loading room XY" is shown.

Any News here?

----------------------------------------------------------------------


NVM:
Similar Issue as here
https://github.com/RocketChat/Rocket.Chat.Android/issues/2225
https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy/

**Comment by ugzv** [comment]
Version **3.3.2** fixed the problem for me.

But after you released **3.4.0** yesterday, I am getting the same error message: 
_Sorry, an error has occurred, please try again_

## Logs
```
API ➔ debug GET: /api/v1/emoji-custom
The endpoint "emoji-custom" is deprecated and will be removed after version v1.12.0
Meteor ➔ method listEmojiCustom -> userId: null , arguments: [ {} ]
The endpoint "emoji-custom" is deprecated and will be removed after version 1.12.0
API ➔ debug Success { statusCode: 200,
body:
{ emojis:
[ [Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object] ],
success: true } }
API ➔ debug GET: /api/v1/permissions
The endpoint "permissions" is deprecated and will be removed after version v0.69
API ➔ debug Success { statusCode: 200,
body:
[ { _id: 'access-mailer',
roles: [Array],
_updatedAt: 2019-05-10T13:16:47.441Z },
{ _id: 'access-permissions',
roles: [Array],
_updatedAt: 2018-09-06T07:37:31.981Z },
{ _id: 'add-oauth-service',
roles: [Array],
_updatedAt: 2018-09-06T07:37:31.984Z },
{ _id: 'add-user-to-any-c-room',
roles: [Array],
_updatedAt: 2018-09-06T07:37:31.991Z },
{ _id: 'add-user-to-any-p-room',
roles: [Array],
_updatedAt: 2018-09-06T08:11:37.418Z },
{ _id: 'add-user-to-joined-room',
roles: [Array],
_updatedAt: 2018-09-06T07:37:31.988Z },
{ _id: 'api-bypass-rate-limit',
roles: [Array],
_updatedAt: 2019-02-24T23:55:55.789Z },
{ _id: 'archive-room',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.025Z },
{ _id: 'assign-admin-role',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.028Z },
{ _id: 'assign-roles',
roles: [Array],
_updatedAt: 2019-04-28T18:31:16.932Z },
{ _id: 'auto-translate',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.510Z },
{ _id: 'ban-user',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.031Z },
{ _id: 'bulk-create-c',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.034Z },
{ _id: 'bulk-register-user',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.037Z },
{ _id: 'call-management',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.440Z },
{ _id: 'clean-channel-history',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.053Z },
{ _id: 'close-livechat-room',
roles: [Array],
_updatedAt: 2019-05-10T13:16:47.453Z },
{ _id: 'close-others-livechat-room',
roles: [Array],
_updatedAt: 2019-05-10T13:16:47.455Z },
{ _id: 'create-c',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.041Z },
{ _id: 'create-d',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.044Z },
{ _id: 'create-p',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.048Z },
{ _id: 'create-personal-access-tokens',
roles: [Array],
_updatedAt: 2018-11-28T18:38:26.696Z },
{ _id: 'create-user',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.051Z },
{ _id: 'delete-c',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.056Z },
{ _id: 'delete-d',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.060Z },
{ _id: 'delete-message',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.068Z },
{ _id: 'delete-p',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.071Z },
{ _id: 'delete-user',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.074Z },
{ _id: 'edit-message',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.077Z },
{ _id: 'edit-other-user-active-status',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.081Z },
{ _id: 'edit-other-user-avatar',
roles: [Array],
_updatedAt: 2019-04-28T18:31:16.947Z },
{ _id: 'edit-other-user-info',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.254Z },
{ _id: 'edit-other-user-password',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.259Z },
{ _id: 'edit-privileged-setting',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.262Z },
{ _id: 'edit-room',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.265Z },
{ _id: 'edit-room-retention-policy',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.269Z },
{ _id: 'force-delete-message',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.272Z },
{ _id: 'join-without-join-code',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.275Z },
{ _id: 'leave-c',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.278Z },
{ _id: 'leave-p',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.281Z },
{ _id: 'mail-messages',
roles: [Array],
_updatedAt: 2019-05-10T13:16:46.138Z },
{ _id: 'manage-apps',
roles: [Array],
_updatedAt: 2019-05-10T13:16:43.599Z },
{ _id: 'manage-assets',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.284Z },
{ _id: 'manage-cloud',
roles: [Array],
_updatedAt: 2019-05-10T13:16:26.051Z },
{ _id: 'manage-emoji',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.287Z },
{ _id: 'manage-integrations',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.291Z },
{ _id: 'manage-oauth-apps',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.302Z },
{ _id: 'manage-own-integrations',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.293Z },
{ _id: 'manage-sounds',
roles: [Array],
_updatedAt: 2019-05-10T13:16:46.199Z },
{ _id: 'mention-all',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.310Z },
{ _id: 'mention-here',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.313Z },
{ _id: 'mute-user',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.316Z },
{ _id: 'pin-message',
roles: [Array],
_updatedAt: 2019-05-10T13:16:46.426Z },
{ _id: 'post-readonly',
roles: [Array],
_updatedAt: 2019-05-10T13:16:46.130Z },
{ _id: 'preview-c-room',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.432Z },
{ _id: 'remove-closed-livechat-rooms',
roles: [Array],
_updatedAt: 2019-05-10T13:16:47.460Z },
{ _id: 'remove-user',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.322Z },
{ _id: 'reset-other-user-e2e-key',
roles: [Array],
_updatedAt: 2018-11-28T18:38:26.718Z },
{ _id: 'run-import',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.326Z },
{ _id: 'run-migration',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.329Z },
{ _id: 'save-others-livechat-room-info',
roles: [Array],
_updatedAt: 2019-05-10T13:16:47.458Z },
{ _id: 'send-many-messages',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.342Z },
{ _id: 'set-leader',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.345Z },
{ _id: 'set-moderator',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.334Z },
{ _id: 'set-owner',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.337Z },
{ _id: 'set-react-when-readonly',
roles: [Array],
_updatedAt: 2019-05-10T13:16:46.135Z },
{ _id: 'set-readonly',
roles: [Array],
_updatedAt: 2019-05-10T13:16:46.133Z },
{ _id: 'snippet-message',
roles: [Array],
_updatedAt: 2019-05-10T13:16:46.434Z },
{ _id: 'start-discussion',
roles: [Array],
_updatedAt: 2019-04-28T18:31:28.830Z },
{ _id: 'start-discussion-other-user',
roles: [Array],
_updatedAt: 2019-04-28T18:31:28.888Z },
{ _id: 'unarchive-room',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.348Z },
{ _id: 'user-generate-access-token',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.354Z },
{ _id: 'view-broadcast-member-list',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.437Z },
{ _id: 'view-c-room',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.351Z },
{ _id: 'view-d-room',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.357Z },
{ _id: 'view-full-other-user-info',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.371Z },
{ _id: 'view-history',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.379Z },
{ _id: 'view-join-code',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.392Z },
{ _id: 'view-joined-room',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.389Z },
{ _id: 'view-l-room',
roles: [Array],
_updatedAt: 2019-05-10T13:16:47.445Z },
{ _id: 'view-livechat-analytics',
roles: [Array],
_updatedAt: 2019-05-10T13:16:47.463Z },
{ _id: 'view-livechat-manager',
roles: [Array],
_updatedAt: 2019-05-10T13:16:47.448Z },
{ _id: 'view-livechat-rooms',
roles: [Array],
_updatedAt: 2019-05-10T13:16:47.450Z },
{ _id: 'view-logs',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.399Z },
{ _id: 'view-other-user-channels',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.402Z },
{ _id: 'view-outside-room',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.434Z },
{ _id: 'view-p-room',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.408Z },
{ _id: 'view-privileged-setting',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.411Z },
{ _id: 'view-room-administration',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.421Z },
{ _id: 'view-statistics',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.424Z },
{ _id: 'view-user-administration',
roles: [Array],
_updatedAt: 2018-09-06T07:37:32.429Z },
success: true ] }
API ➔ debug GET: /api/v1/settings.public?count=0&fields=%7B%22type%22%3A%201%7D&query=%7B%22_id%22%3A%20%7B%22%24in%22%3A%20%5B%22uniqueID%22%2C%22LDAP_Enable%22%2C%22CAS_enabled%22%2C%22CAS_login_url%22%2C%22Accounts_RegistrationForm%22%2C%22Accounts_ShowFormLogin%22%2C%22Accounts_PasswordReset%22%2C%22Accounts_CustomFields%22%2C%22Accounts_OAuth_Google%22%2C%22Accounts_OAuth_Facebook%22%2C%22Accounts_OAuth_Github%22%2C%22Accounts_OAuth_Linkedin%22%2C%22Accounts_OAuth_Meteor%22%2C%22Accounts_OAuth_Twitter%22%2C%22Accounts_OAuth_Gitlab%22%2C%22API_Gitlab_URL%22%2C%22Accounts_OAuth_Wordpress%22%2C%22API_Wordpress_URL%22%2C%22Jitsi_Enabled%22%2C%22Jisti_Enable_Channels%22%2C%22Jitsi_SSL%22%2C%22Jitsi_Domain%22%2C%22Jitsi_URL_Room_Prefix%22%2C%22Site_Url%22%2C%22Site_Name%22%2C%22Assets_favicon_512%22%2C%22Assets_favicon_192%22%2C%22UI_Use_Real_Name%22%2C%22UI_Allow_room_names_with_special_chars%22%2C%22Favorite_Rooms%22%2C%22FileUpload_Storage_Type%22%2C%22FileUpload_MaxFileSize%22%2C%22FileUpload_MediaTypeWhiteList%22%2C%22Message_HideType_uj%22%2C%22Message_HideType_ul%22%2C%22Message_HideType_au%22%2C%22Message_HideType_mute_unmute%22%2C%22Message_HideType_ru%22%2C%22Message_AllowDeleting%22%2C%22Message_AllowEditing%22%2C%22Message_AllowPinning%22%2C%22Message_AllowStarring%22%2C%22Message_ShowDeletedStatus%22%2C%22Message_ShowEditedStatus%22%2C%22Assets_tile_310_wide%22%2C%22Store_Last_Message%22%2C%22Message_Read_Receipt_Enabled%22%2C%22Message_Read_Receipt_Store_Users%22%5D%7D%7D
API ➔ debug Success { statusCode: 200,
body:
{ settings:
[ [Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object] ],
count: 47,
offset: 0,
total: 47,
success: true } }
API ➔ debug POST: /api/v1/push.token
API ➔ debug Success { statusCode: 200,
body:
{ result:
{ _id: 'bqQ3WSW9cB7oQrftG',
token: [Object],
appName: 'Main',
userId: '4ZZYv2CfFrxcK9bQL',
enabled: true,
createdAt: 2019-05-10T04:29:24.579Z,
updatedAt: 2019-05-16T10:54:58.693Z },
success: true } }
Meteor ➔ publish null -> userId: null , arguments: []
Meteor ➔ publish null -> userId: 4ZZYv2CfFrxcK9bQL , arguments: []
API ➔ debug GET: /api/v1/rooms.get
Meteor ➔ method rooms/get -> userId: 4ZZYv2CfFrxcK9bQL , arguments: [ undefined ]
API ➔ debug Success { statusCode: 200,
body:
{ update:
[ [Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object],
[Object] ],
remove: [],
success: true } }
Meteor ➔ publish userData -> userId: 4ZZYv2CfFrxcK9bQL , arguments: []
Meteor ➔ publish activeUsers -> userId: 4ZZYv2CfFrxcK9bQL , arguments: []
Meteor ➔ method UserPresence:online -> userId: 4ZZYv2CfFrxcK9bQL , arguments: []
```

**Comment by andypost** [comment]
The same failure after upgrade to 3.4.0 - the same chats are inaccessible but now no error message displayed

**Comment by Crazy-Hopper** [comment]
Well, I've found that be it version 3.3.2 or 3.4.0, there is a flow which involves searching, selecting some chats, pressing backs, etc (can't formalize it yet) after which the chat list becomes functional...

**Comment by dcook1313** [comment]
we are getting the exact same thing as OP on samsungs note 9 and on one s7 while it works fine on a different S7.

**Comment by ChrissW-R1** [comment]
> we are getting the exact same thing as OP on samsungs note 9 and on one s7 while it works fine on a different S7.

We also have this issue on Samsung Galaxy S7. So I don't think the device matters.

**Comment by all3kcis** [comment]
I have the same problem. I think it's a bug in the application because if I search for a private conversation and click on it, I get an error. But if I go back to the main application page, the conversation appears in the list and if I click on it I can read the messages.

**Comment by Cosmos-Web** [comment]
A similar problem, on the part of mobile devices works, on the part - does not work.
The position was saved by the application “Rocket.Chat Experimental” - everything is working correctly in it.

Server version: 1.0.3

**Comment by dcook1313** [comment]
thank you,  So we should try the "experimental" version?

**Comment by all3kcis** [comment]
**Yesterday :**  
Same here, 
Server version: 1.0.3
Works with experimental app version..

EDIT; Today is ok with app 3.4.1.. I don't know why ... Nothing has changed on my side since yesterday

**Comment by Siorde** [comment]
I had the same issue. Server in 1.0.3, app in 3.4.1, and working fine on the experimental version.
We had to restart the server today and then it work fine on the android app.
So, maybe a server reboot solve the issue.
Now, we need to be sure it won't happen again.

**Comment by all3kcis** [comment]
My server hasn't been restarted for 3 days and yet today it works... 
Looks like there's a third party service hiding in there.

**Comment by ugzv** [comment]
> My server hasn't been restarted for 3 days and yet today it works...
> Looks like there's a third party service hiding in there.

The server setup was not questionable here, but Android app version. Most likely your app got updated and now it works.

**Comment by all3kcis** [comment]
No, app was already in version 3.4.1 yesterday and it didn't work, that for 3 phones ( samsung galaxy ).

**Comment by Siorde** [comment]
Same here, i already was in 3.4.1 yesterday and it didn't work.

**Comment by dcook1313** [comment]
The Same here. We are using the latest live rocketchat release 3.4.1.  its all on Samsungs that we are having the issue on.

**Comment by philipbrito** [comment]
@nopynoop and @andypost Is the `3.4.1 (2069)` native Android version working for both of you?

**Comment by philipbrito** [comment]
@all3kcis, @Siorde @dcook1313 and possible others here that are still facing that bug with `3.4.1 (2069)`, do you guys care creating a test user account to me on your servers? This way I can try to simulate what is going wrong. If so, please contact me on our open server [here](https://open.rocket.chat/direct/filipe.brito).

**Comment by ugzv** [comment]
> @nopynoop and @andypost Is the `3.4.1 (2069)` native Android version working for both of you?

I can confirm that the `3.4.1 (2069)` is working fine for me.

The server version is still `1.0.3`.

**Comment by dcook1313** [comment]
I'm sorry Filipe, I am not able, I am not the admin of the server where RocketChat resides, just a middleman.   
 The Admin has it locked down so only he can create new user accounts.  
I'm also not a programmer so forgive me if this is a stupid question, is it possible to get the older version of the android application to use until this is sorted? Will it still work if we can?  All I know is that we have several techs, another one added today, all complaining that rocket chat on their Android devices is not working correctly and they keep getting the "An Error Has Occured" message when trying to view messages on it.  Again its not on every device, have 2 samsung 7s that for the most part it works on one and not the other.  It doesn't matter if its uninstalled and reinstalled etc.

thank you :)

**Comment by Siorde** [comment]
I had the problem 2 days ago and i already was on 3.4.1. But since i restarted the server yesterday it is working.

**Comment by philipbrito** [comment]
@dcook1313 Downgrading the app version is not a good thing to do (we have lots of features, improvements and bug fixes done from the past release - as an example the last Android app version has more than 50 PRs merged). Downgrading will be a crazy situation, believe me (but you are free to try it locally). 

We really need to have our last version working for all users and we are trying to do all best to understand and consequently fix the bug. What happens when you restart your server (as done by @Siorde)? Did you try doing it? If not, could you try?

**Comment by dcook1313** [comment]
thank you Filipe, thank you for the info. I would so just do this myself if
I could.  Im going to ask to see if they can reset the server with Rocket
Chat on it. Ill try getting back to you as soon as I can get them to do
it.  thank you again

**Comment by Cosmos-Web** [comment]
@filipedelimabrito,
I included logging on the server and compared logs of users - those who do not work and those who work.
It is very likely that for the first to one of the requests, an array with objects is given, and for the second, an array with arrays.
The reason for this I could not find, the settings for these users are the same.
Today, before the end of the day, I will try to make a comparison and attach logs here.

**Comment by philipbrito** [comment]
Thanks @Cosmos-Web! As soon as you make the comparison let us know by attaching the logs here.

**Comment by Cosmos-Web** [comment]
@filipedelimabrito 
Magic!
I apologize, but as soon as I was going to collect logs - it turned out that today everything works correctly for everyone.

I have an assumption - maybe there is some kind of data or versioning caching? Those. some time for some users received answers from the server in the old version?
Because we had a server version 0.73.2, the mobile application was updated to the latest version and stopped working. Then I updated the server to 1.0.3, and some users still have a cache?
And now, after some time, everything began to work correctly.

PS: I restarted the server several times, but this did not solve the problem. Everything worked over time.
P.P.S .: Our server is in the Docker container.

**Comment by peterkogit** [comment]
Similar problem Samsung A5 2017
Server version 1.0.3
Application version 3.4.1

The application was installed recently, the server is installed and updates via Snaps

**Comment by all3kcis** [comment]
The problem seems to have resolved itself on some phones.
But still present on a Galaxy A8
Server version 1.0.3 (manual install on Debian 9)
Application version 3.4.1

Additional information, (On Samsung A8)
If I click on the "Administration" tab, the general channel is loaded! 
The administration page is therefore not accessible but allows you to display the general channel... Realy Strange!

**Comment by peterkogit** [comment]
All the same problem on ASUS ZC554KL
8.1.0 version of Android
Server version 1.0.3
Application version 3.4.1

Also logs on the server as written above

**Comment by follower46** [comment]
From my testing over the past few days it appears that the channel list doesn't automatically update (this is for app version 3.4.1 / server 1.0.3).
I have conversations which shows the "last message" from hours or days ago.
I am able to force an update by either starting a new conversation with a contact or clicking "message" from a contact's profile.
This updates the list and allows me to mitigate the issues on my android devices.

**Comment by antgel** [comment]
I opened #2341 for this, then @all3kcis kindly pointed out it was a duplicate. Full details (and screenshots) in that bug. Summary: Android 3.4.1, server 1.0.3, docker-compose, nginx.

Happy to give RC team members access to server to help debug this, users are suffering and RC is becoming useless for us. :(

I'll add nginx configuration which was not in the original Issue, it might be useful:

```
 server {
   listen 443 ssl http2;
   server_name rocketchat.MUNGED.com;
    ssl_certificate /etc/letsencrypt/live/rocketchat.MUNGED.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/rocketchat.MUNGED.com/privkey.pem; # managed by Certbot
   ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
   ssl_prefer_server_ciphers on;
   ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
   root /usr/share/nginx/html;
   index index.html index.htm;
   # Make site accessible from http://localhost/
   server_name localhost;
   location / {
     proxy_pass http://localhost:3000/;
     proxy_http_version 1.1;
     proxy_set_header Upgrade $http_upgrade;
     proxy_set_header Connection "upgrade";
     proxy_set_header Host $http_host;
     proxy_set_header X-Real-IP $remote_addr;
     proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
     proxy_set_header X-Forward-Proto http;
     proxy_set_header X-Nginx-Proxy true;
     proxy_redirect off;
   }

}
 server {
    if ($host = rocketchat.MUNGED.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

   listen 80;
   server_name rocketchat.MUNGED.com;
   return 301 https://$host$request_uri;
}
```

**Comment by peterkogit** [comment]
As practice shows, this is a problem for users.
I go from one device under different users, one has an error for the second one.

**Comment by antgel** [comment]
@peterkogit I think it happens to most if not all of our users (many tend not to point out issues and just stop using the tool). Are there any specific differences between the two users you mention?

**Comment by peterkogit** [comment]
@antgel There are no strong differences between them.
The first is just an employee of the company. The second test user, but he has all the same powers.

The only difference is that an employee of the company actively rewritten and throws off various fights.

**Comment by all3kcis** [comment]
I just made a new installation of Docker server (v1.0.3), Android 3.4.1 app works correctly.
Then I imported the backup from my real server. And then the mistakes come back.
Concerning the real server I upgraded from version 0.74.3 to 1.0.3  last week.

Maybe there was a problem during the migration?

Some infos :
When I do a search if I click on a channel either it is displayed but there is no message, or I have the error `Expected END_OBJECT but  was END_DOCUMENT at path $`
On channels where I don't have a message I get the following error in the server logs :
```
Exception in defer callback: TypeError: Cannot read property 'ls' of undefined
    at Meteor.defer (server/methods/readMessages.js:25:81)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
    at packages/meteor.js:620:25
    at runWithEnvironment (packages/meteor.js:1356:24)
```
Others things : 
On android app connected to fresh installed server, emoji are not display when I click to "add reaction" (works on android app connected to real server ...)

On android app connected to fresh installed server, I can access to "Administration" link, on android app connected to real server I can not, it display defaut channel.

**Comment by dcook1313** [comment]
hi Guys, after they rebooted the server, it appears to be working for the
te techs now.  thank you

**Comment by northway** [comment]
The problem is still in effect:
Huawei P9 Lite and Samung Galaxy S8
Server version 1.1.0 (manual install on Debian 9)
Application version 3.4.1 (Play Store)

Neither logout or reinstalling the app worked so far.

**Comment by Exordian** [comment]
I just debugged this issue in my own interest, and found the problematic logic. The state machine in the SDK for the `RoomListAdapter` has a wrong assumption on an object end. @filipedelimabrito already prepared a fix in https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK/pull/250 , a longside with a lot of other changes. The change needed to resolve this particular issue is https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK/pull/250/commits/1347a0a97060dbca0fcb2d329760230268249b0d . I'd be glad if @filipedelimabrito would be able to finialize this PR and releases a new version, with the updated logic.

/E: FWIW, additional info: tested against server version 0.74.3

**Comment by hkbnman** [comment]
Very good to know the solution of the problem,  but will it fix the "The required "roomId" or "roomname" param provided does not match any channel [error-room-not-found]" issue?

**Comment by antgel** [comment]
@filipedelimabrito In response to @Exordian 's comment, can we get a hotfix? The application is broken for many people in production.

**Comment by philipbrito** [comment]
@antgel We are doing our best to fix this issue. Sorry for that.

**Comment by philipbrito** [comment]
For those having **this problem** (and for those already able to see the chat list) could you guys try this [apk](https://12641-48179404-gh.circle-artifacts.com/0/apks/play/release/app-play-release.apk) ? 

We are going to release a new app version on Play Store, but it'd be great if you all can confirm us that it is working as expected now.

**Comment by hfeky** [comment]
@filipedelimabrito I confirm it is working very well for me, and all chat rooms are visible now. All emoji reactions are working as well, so issue #2288 can also get closed if it is working for all others. :tada:

**Comment by peterkogit** [comment]
@filipedelimabrito Chats with new apk work. Let's hope that the problem will be solved.

**Comment by tomkeiev** [comment]
@filipedelimabrito 3.4.2 works for me (Samsung S8 Android 9.0)
thanks for the fix and giving the apk

**Comment by antgel** [comment]
@filipedelimabrito Thanks for dealing with the issue. Has the .apk been submitted to the Play Store for approval?

**Comment by philipbrito** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat.Android/pull/2352

**Comment by philipbrito** [comment]
@antgel Yes.

**Comment by magnetic5355** [comment]
This issue has occurred for the first time for me after the update to 3.5.

Running 1.1.3 via Snap

Reset app, uninstalled reinstalled, restarted server. 

I have a blank chat list, can search but not message. 

Receive "sorry an unknown error has occurred"

**Comment by philipbrito** [comment]
@caesarcxiv Still happening to you? 🤔

**Comment by magnetic5355** [comment]
Yes

**Comment by 1c4nw1n** [comment]
same error on APK v 3.5.0

**Comment by 1c4nw1n** [comment]
also noticed errors like this in nginx log (using as reverse proxy)
GET /api/v1/rooms.get HTTP/1.1 400

**Comment by magnetic5355** [comment]
Issue resolved itself for a couple days and is now back.

Snap updated to 1.2.3 in the meantime.
