### ISSUE TITLE
[NEW] Support to login with custom OAuth

### ISSUE THREAD

**Issue by kamlesh-grmtech** [RocketChat/Rocket.Chat.Android#322]
Your Rocket.Chat.Android version: (make sure you are running the latest)

**Comment by matheusjardimb** [comment]
Hello there, thanks for contributing!

@kamlesh-grmtech What is your "custom auth"? Is it OAuth (Facebook, Google, Github...)? If so, you may consider taking a look here https://rocket.chat/docs/administrator-guides/authentication/oauth

@geekgonecrazy any extra comments?

**Comment by geekgonecrazy** [comment]
I'm not 100% positive but I believe all of the oauth methods are supported.  I think only ones not yet in the app maybe:
* LDAP
* SAML
* CAS

**Comment by kamlesh-grmtech** [comment]
@matheusjardimb If you check the Rocket chat web version then you will find the custom OAuth.
I have created my custom OAuth to login in the web version. But now I am unable to login in the rocket chat+ . it is saying password not set for the user.

**Comment by matheusjardimb** [comment]
Sorry @kamlesh-grmtech but I didn't get it. 
If you install this version https://play.google.com/store/apps/details?id=chat.rocket.android and connect to demo.rocket.chat you'll see multiple auth providers, right?

![image](https://user-images.githubusercontent.com/468794/27181927-f43ebd16-51af-11e7-9caf-ef7386788189.png)

This auth providers are configured at the server side, not the app side.  

Are you talking about a different provider than the ones listed in the app? 
What `custom` really means?

**Comment by geekgonecrazy** [comment]
So actually I was mistaken when I said we already supported custom oauth.

Here is what we have on the demo server:

![image](https://user-images.githubusercontent.com/51996/27208593-2ce08666-520c-11e7-95d3-0fdf1ac73766.png)

You'll notice the little blue one next to twitter.  I just added that as a custom oauth provider.  It doesn't show in the app.  It appears the app only supports: 
* twitter
* facebook
* github
* google apps

So I guess we still need to support custom oauth providers :smile:

**Comment by matheusjardimb** [comment]
@geekgonecrazy Yep, we currently only support Github, Google, Facebook and Twitter in the app.

@kamlesh-grmtech you probably want to take a look into package chat.rocket.android.fragment.oauth in order to see how we implemented those providers and to get what'd take to implement a new one.

Hope that helps :)

**Comment by rafaelks** [comment]
Closing this one due to inactivity.

**Comment by mateusmedeiros** [comment]
Shouldn't this be left open since the issue still exists? Or is there no intention to support login through custom oauth providers on the native android client?

**Comment by rafaelks** [comment]
@mateusmedeiros Yes, there is in `v2`. I'll let this issue opened and update the information. Thanks!

**Comment by cristiandley** [comment]
@mateusmedeiros any news about this feature ? I'm in need of something like that

**Comment by rafaelks** [comment]
@cristiandley We're working on this one for v2.

**Comment by cristiandley** [comment]
@rafaelks 

Im trying to implment AbstractOAuthFrament class

public class DgiOAuthFragment extends AbstractOAuthFragment {

  @Override
  protected String getOAuthServiceName() {
    return "dgi";
  }

  @Override
  protected String generateURL(LoginServiceConfiguration oauthConfig) {
    return new HttpUrl.Builder().scheme("http")
        .host("http://1.1.1.1:1111")
        .addQueryParameter("client_id", "xyz123")
        .addQueryParameter("display", "popup")
        .addQueryParameter("scope", "email")
        .addQueryParameter("state", getStateString())
        .build()
        .toString();
  }
}
But my main issue is i dont know how to implement the:

Token Path
Identity Path
Authorize Path

I didnt found enough documentation to know what to do

**Comment by rafaelks** [comment]
@cristiandley You should have this values from the WebSocket (in Settings). Are you receiving it?

**Comment by cristiandley** [comment]
@rafaelks Maybe I expressed myself wrong. Im asking more about documentation than anything else... 

i dont know if `.addQueryParameter("tokenPath", ")` exists and the other ones i asked :cry:

**Comment by rafaelks** [comment]
@cristiandley Not sure I follow your question... what do you wanna do?

**Comment by cristiandley** [comment]
I started to work on a PR based on https://github.com/RocketChat/Rocket.Chat.iOS/pull/804

I identfied 3 mains changes we must work on:

- [x] Retrieve login services from server
- [x] Insert custom OAuth buttons in login screen 
- [x] Assign action to login service button  
- [ ] Detect if service is custom service **(any idea on this one ?)**

I'v been playing with the app... and trying to get familiar with it. Im a bit lost with a section:

```java
Rocket.Chat.Android/app/src/main/java/chat/rocket/android/layouthelper/oauth/OAuthProviderInfo.java
````

- Seems to hardcode the Providers ?
- Should it get the services from the server ?
- Or should CustomProvider be another one there ?


```java
Rocket.Chat.Android/app/src/main/java/chat/rocket/android/fragment/server_config/LoginFragment.kt
```

```override fun showLoginServices(loginServiceList: List<LoginServiceConfiguration>)```

Allow or not the Providers to be shown on the login screen...

- where does the visibility is obtain ?

```
/Rocket.Chat.Android/persistence-realm/src/main/java/chat/rocket/persistence/realm/repositories/RealmLoginServiceConfigurationRepository.java
``` 

Seems to add the services on 77

 ``` 
serviceConfigurations.add(realmConfigurations.get(i).asLoginServiceConfiguration());
``` 

*the visibility still not there...*

Thanks

**Comment by markwooff** [comment]
First off, just wanted to thank you all for the hard work you do towards enhancing the RocketChat platform. Our organization has been following along with these recent changes pretty closely. I'm just wondering if this feature will for sure be coming out as part of v2.0.1? We rely on an OpenID login which is not being shown at all on Android devices. Thanks in advance :)

**Comment by rafaelks** [comment]
@markwooff Thank you for the question and for the feedback! We're still waiting for this fix in our API to be merged before we add the support in the app: https://github.com/RocketChat/Rocket.Chat/pull/10299. We're planning to do that for next release in our back-end by 27th, so probably version 2.0.3 or 2.0.2 will have it. 👍

**Comment by KyleKotowick** [comment]
Lots of comments regarding OAuth and SSO, but is [iFrame auth](https://rocket.chat/docs/developer-guides/iframe-integration/authentication/) going to be supported soon as well? I have this working on my website, but on the Android app it just shows a blank screen.

**Comment by rafaelks** [comment]
@kkotowick Could you create an issue for that please? This isn't going to be address together with this one.

To all others following this topic: we do plan to include Custom OAuth very soon into our builds.

**Comment by KyleKotowick** [comment]
@rafaelks I did, #709, then you closed it and linked it to this one. You're sending mixed messages here.

**Comment by rafaelks** [comment]
@kkotowick Ups, sorry about that, just reopened. Realised they're different implementations. 👍
